FROM golang:1.15-alpine

RUN apk add --no-cache git

# Set the current working directory inside the container
WORKDIR /golang-templateapi

# We want to populate the module cache based on the go.{mod,sum} files
COPY go.mod .
COPY go.sum .

RUN go mod download

COPY . .

# Build the app

RUN go run automation/populate-users/main.go \
    -DATABASE_PORT=5432 \
    -DATABASE_USER="postgres" \
    -DATABASE_PASS="docker" \
    -DATABASE_HOST="localhost"